import { appSchema as createSchema, tableSchema } from '@nozbe/watermelondb';

export const appSchema = createSchema({
  version: 19,
  tables: [
    tableSchema({
      name: 'series',
      columns: [
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'dtstart_local', type: 'string' },
        { name: 'dtstart_utc', type: 'string' },
        { name: 'timezone', type: 'string' },
        { name: 'rrule', type: 'string' },
        { name: 'until_utc', type: 'string', isOptional: true },
        { name: 'count', type: 'number', isOptional: true },
        { name: 'plant_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'occurrence_overrides',
      columns: [
        { name: 'series_id', type: 'string' },
        { name: 'occurrence_local_date', type: 'string' },
        { name: 'due_at_local', type: 'string', isOptional: true },
        { name: 'due_at_utc', type: 'string', isOptional: true },
        { name: 'reminder_at_local', type: 'string', isOptional: true },
        { name: 'reminder_at_utc', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'tasks',
      columns: [
        { name: 'series_id', type: 'string', isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'due_at_local', type: 'string' },
        { name: 'due_at_utc', type: 'string' },
        { name: 'timezone', type: 'string' },
        { name: 'reminder_at_local', type: 'string', isOptional: true },
        { name: 'reminder_at_utc', type: 'string', isOptional: true },
        { name: 'plant_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'metadata', type: 'string' },
        { name: 'playbook_id', type: 'string', isOptional: true },
        { name: 'origin_step_id', type: 'string', isOptional: true },
        { name: 'phase_index', type: 'number', isOptional: true },
        { name: 'notification_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'notification_queue',
      columns: [
        { name: 'task_id', type: 'string' },
        { name: 'notification_id', type: 'string' },
        { name: 'scheduled_for_local', type: 'string' },
        { name: 'scheduled_for_utc', type: 'string' },
        { name: 'timezone', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'notifications',
      columns: [
        { name: 'type', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'body', type: 'string' },
        { name: 'data', type: 'string' },
        { name: 'deep_link', type: 'string', isOptional: true },
        { name: 'read_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        {
          name: 'expires_at',
          type: 'number',
          isOptional: true,
          isIndexed: true,
        },
        {
          name: 'message_id',
          type: 'string',
          isOptional: true,
          isIndexed: true,
        },
        {
          name: 'archived_at',
          type: 'number',
          isOptional: true,
          isIndexed: true,
        },
        {
          name: 'deleted_at',
          type: 'number',
          isOptional: true,
          isIndexed: true,
        },
      ],
    }),
    tableSchema({
      name: 'notification_preferences',
      columns: [
        // Uniqueness by user_id is enforced at the application level via findOrCreate/upsert methods
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'community_interactions', type: 'boolean' },
        { name: 'community_likes', type: 'boolean' },
        { name: 'cultivation_reminders', type: 'boolean' },
        { name: 'system_updates', type: 'boolean' },
        { name: 'quiet_hours_enabled', type: 'boolean' },
        { name: 'quiet_hours_start', type: 'string', isOptional: true },
        { name: 'quiet_hours_end', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'device_tokens',
      columns: [
        { name: 'token', type: 'string', isIndexed: true },
        { name: 'platform', type: 'string' },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'last_used_at', type: 'number' },
        { name: 'is_active', type: 'boolean', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'image_upload_queue',
      columns: [
        { name: 'local_uri', type: 'string' },
        { name: 'remote_path', type: 'string', isOptional: true },
        { name: 'task_id', type: 'string', isOptional: true },
        { name: 'plant_id', type: 'string', isOptional: true },
        { name: 'harvest_id', type: 'string', isOptional: true },
        { name: 'variant', type: 'string', isOptional: true },
        { name: 'hash', type: 'string', isOptional: true },
        { name: 'extension', type: 'string', isOptional: true },
        { name: 'filename', type: 'string', isOptional: true },
        { name: 'mime_type', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true }, // pending | uploading | completed | failed
        { name: 'retry_count', type: 'number', isOptional: true },
        { name: 'last_error', type: 'string', isOptional: true },
        {
          name: 'next_attempt_at',
          type: 'number',
          isOptional: true,
          isIndexed: true,
        },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    // Strains Browser Tables
    tableSchema({
      name: 'favorites',
      columns: [
        { name: 'strain_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'added_at', type: 'number', isIndexed: true },
        { name: 'snapshot', type: 'string' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'cached_strains',
      columns: [
        { name: 'query_hash', type: 'string', isIndexed: true },
        { name: 'page_number', type: 'number', isIndexed: true },
        { name: 'strains_data', type: 'string' },
        { name: 'cached_at', type: 'number' },
        { name: 'expires_at', type: 'number', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    // Guided Grow Playbooks Tables
    tableSchema({
      name: 'playbooks',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'setup', type: 'string' }, // auto_indoor | auto_outdoor | photo_indoor | photo_outdoor
        { name: 'locale', type: 'string' },
        { name: 'phase_order', type: 'string' }, // JSON array of phases
        { name: 'steps', type: 'string' }, // JSON array of PlaybookStep
        { name: 'metadata', type: 'string' }, // JSON PlaybookMetadata
        { name: 'is_template', type: 'boolean' },
        { name: 'is_community', type: 'boolean' },
        { name: 'author_handle', type: 'string', isOptional: true },
        { name: 'license', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'playbook_applications',
      columns: [
        { name: 'playbook_id', type: 'string', isIndexed: true },
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'applied_at', type: 'number', isIndexed: true },
        { name: 'task_count', type: 'number' },
        { name: 'duration_ms', type: 'number' },
        { name: 'job_id', type: 'string' },
        {
          name: 'idempotency_key',
          type: 'string',
          isOptional: true,
          isIndexed: true,
        },
        { name: 'status', type: 'string' }, // pending | completed | failed
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'undo_descriptors',
      columns: [
        { name: 'operation_type', type: 'string' },
        { name: 'affected_task_ids', type: 'string' }, // JSON array
        { name: 'prior_field_values', type: 'string' }, // JSON object
        { name: 'timestamp', type: 'number', isIndexed: true },
        { name: 'expires_at', type: 'number', isIndexed: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'outbox_notification_actions',
      columns: [
        { name: 'action_type', type: 'string' },
        { name: 'payload', type: 'string' }, // JSON object
        {
          name: 'business_key',
          type: 'string',
          isOptional: true,
          isIndexed: true,
        },
        { name: 'ttl', type: 'number' },
        { name: 'expires_at', type: 'number', isIndexed: true },
        { name: 'next_attempt_at', type: 'number', isIndexed: true },
        { name: 'attempted_count', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'last_error', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'ai_suggestions',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'suggestion_type', type: 'string' },
        { name: 'reasoning', type: 'string' },
        { name: 'affected_tasks', type: 'string' }, // JSON array
        { name: 'confidence', type: 'number' },
        {
          name: 'cooldown_until',
          type: 'number',
          isOptional: true,
          isIndexed: true,
        },
        { name: 'expires_at', type: 'number', isIndexed: true },
        { name: 'status', type: 'string' }, // pending | accepted | declined
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'trichome_assessments',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'assessment_date', type: 'string' },
        { name: 'clear_percent', type: 'number', isOptional: true },
        { name: 'milky_percent', type: 'number', isOptional: true },
        { name: 'amber_percent', type: 'number', isOptional: true },
        { name: 'photos', type: 'string', isOptional: true }, // JSON array of URIs
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'harvest_window_suggestion', type: 'string', isOptional: true }, // JSON object
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'adjustment_suggestions',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'playbook_id', type: 'string', isOptional: true },
        { name: 'suggestion_type', type: 'string' },
        { name: 'root_cause', type: 'string' },
        { name: 'reasoning', type: 'string' },
        { name: 'affected_tasks', type: 'string' }, // JSON array of task adjustments
        { name: 'confidence', type: 'number' },
        { name: 'status', type: 'string' }, // pending | accepted | declined | expired
        { name: 'accepted_tasks', type: 'string', isOptional: true }, // JSON array of accepted task IDs
        { name: 'helpfulness_vote', type: 'string', isOptional: true }, // helpful | not_helpful
        { name: 'expires_at', type: 'number', isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'adjustment_cooldowns',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'root_cause', type: 'string', isIndexed: true },
        { name: 'cooldown_until', type: 'number', isIndexed: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'plant_adjustment_preferences',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'never_suggest', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'harvests',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'stage', type: 'string', isIndexed: true },
        { name: 'wet_weight_g', type: 'number', isOptional: true },
        { name: 'dry_weight_g', type: 'number', isOptional: true },
        { name: 'trimmings_weight_g', type: 'number', isOptional: true },
        { name: 'notes', type: 'string' },
        { name: 'stage_started_at', type: 'number' },
        { name: 'stage_completed_at', type: 'number', isOptional: true },
        { name: 'photos', type: 'string' }, // JSON array of photo URIs
        { name: 'notification_id', type: 'string', isOptional: true }, // Target duration notification
        { name: 'overdue_notification_id', type: 'string', isOptional: true }, // Max duration reminder
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'conflict_seen', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'inventory',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'harvest_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'final_weight_g', type: 'number' },
        { name: 'harvest_date', type: 'string' }, // ISO date string
        { name: 'total_duration_days', type: 'number' },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'harvest_audits',
      columns: [
        { name: 'harvest_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'action', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'from_stage', type: 'string', isOptional: true },
        { name: 'to_stage', type: 'string', isOptional: true },
        { name: 'reason', type: 'string' },
        { name: 'performed_at', type: 'number' },
        { name: 'metadata', type: 'string' }, // JSON
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
        { name: 'server_revision', type: 'number' },
        { name: 'server_updated_at_ms', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'feeding_templates',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'medium', type: 'string' },
        { name: 'phases_json', type: 'string' }, // JSON serialized FeedingPhase[]
        { name: 'target_ranges_json', type: 'string' },
        { name: 'is_custom', type: 'boolean' },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'ph_ec_readings_v2',
      columns: [
        { name: 'plant_id', type: 'string', isOptional: true, isIndexed: true },
        {
          name: 'reservoir_id',
          type: 'string',
          isOptional: true,
          isIndexed: true,
        },
        { name: 'measured_at', type: 'number', isIndexed: true },
        { name: 'ph', type: 'number' },
        { name: 'ec_raw', type: 'number' },
        { name: 'ec_25c', type: 'number' },
        { name: 'temp_c', type: 'number' },
        { name: 'atc_on', type: 'boolean' },
        { name: 'ppm_scale', type: 'string' },
        { name: 'meter_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'quality_flags_json', type: 'string', isOptional: true }, // JSON array of flags
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'reservoirs_v2',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'volume_l', type: 'number' },
        { name: 'medium', type: 'string', isIndexed: true },
        { name: 'target_ph_min', type: 'number' },
        { name: 'target_ph_max', type: 'number' },
        { name: 'target_ec_min_25c', type: 'number' },
        { name: 'target_ec_max_25c', type: 'number' },
        { name: 'ppm_scale', type: 'string' },
        { name: 'source_water_profile_id', type: 'string', isOptional: true },
        { name: 'playbook_binding', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'source_water_profiles_v2',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'baseline_ec_25c', type: 'number' },
        { name: 'alkalinity_mg_per_l_caco3', type: 'number' },
        { name: 'hardness_mg_per_l', type: 'number' },
        { name: 'last_tested_at', type: 'number' },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'calibrations',
      columns: [
        { name: 'meter_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'points_json', type: 'string' },
        { name: 'slope', type: 'number' },
        { name: 'offset', type: 'number' },
        { name: 'temp_c', type: 'number' },
        { name: 'method', type: 'string', isOptional: true },
        { name: 'valid_days', type: 'number', isOptional: true },
        { name: 'performed_at', type: 'number' },
        { name: 'expires_at', type: 'number' },
        { name: 'is_valid', type: 'boolean' },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'deviation_alerts_v2',
      columns: [
        { name: 'reading_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'severity', type: 'string' },
        { name: 'message', type: 'string' },
        { name: 'recommendations_json', type: 'string' },
        { name: 'recommendation_codes_json', type: 'string', isOptional: true },
        { name: 'cooldown_until', type: 'number', isOptional: true },
        { name: 'triggered_at', type: 'number', isIndexed: true },
        { name: 'acknowledged_at', type: 'number', isOptional: true },
        { name: 'resolved_at', type: 'number', isOptional: true },
        { name: 'delivered_at_local', type: 'number', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'reservoir_events',
      columns: [
        { name: 'reservoir_id', type: 'string', isIndexed: true },
        { name: 'kind', type: 'string' }, // 'FILL'|'DILUTE'|'ADD_NUTRIENT'|'PH_UP'|'PH_DOWN'|'CHANGE'
        { name: 'delta_ec_25c', type: 'number', isOptional: true },
        { name: 'delta_ph', type: 'number', isOptional: true },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'diagnostic_results_v2',
      columns: [
        { name: 'plant_id', type: 'string', isIndexed: true },
        {
          name: 'reservoir_id',
          type: 'string',
          isOptional: true,
          isIndexed: true,
        },
        { name: 'water_profile_id', type: 'string', isOptional: true },
        { name: 'issue_type', type: 'string', isIndexed: true },
        { name: 'issue_severity', type: 'string' },
        { name: 'nutrient_code', type: 'string', isOptional: true },
        { name: 'confidence', type: 'number' },
        { name: 'confidence_source', type: 'string' },
        { name: 'rules_confidence', type: 'number', isOptional: true },
        { name: 'ai_confidence', type: 'number', isOptional: true },
        { name: 'confidence_threshold', type: 'number', isOptional: true },
        { name: 'rules_based', type: 'boolean' },
        { name: 'ai_override', type: 'boolean' },
        { name: 'needs_second_opinion', type: 'boolean' },
        { name: 'symptoms_json', type: 'string' },
        { name: 'rationale_json', type: 'string', isOptional: true },
        { name: 'recommendations_json', type: 'string' },
        {
          name: 'recommendation_codes_json',
          type: 'string',
          isOptional: true,
        },
        { name: 'disclaimer_keys_json', type: 'string', isOptional: true },
        { name: 'input_reading_ids_json', type: 'string', isOptional: true },
        { name: 'ai_hypothesis_id', type: 'string', isOptional: true },
        { name: 'ai_metadata_json', type: 'string', isOptional: true },
        { name: 'feedback_helpful_count', type: 'number', isOptional: true },
        {
          name: 'feedback_not_helpful_count',
          type: 'number',
          isOptional: true,
        },
        { name: 'confidence_flags_json', type: 'string', isOptional: true },
        { name: 'resolution_notes', type: 'string', isOptional: true },
        { name: 'resolved_at', type: 'number', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'server_revision', type: 'number', isOptional: true },
        { name: 'server_updated_at_ms', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
  ],
});

// Backwards compatibility export
export const schema = appSchema;
