flows:
  - auth/*
  - app/*

excludeTags:
  - util

executionOrder:
    continueOnFailure: false # default is true
    flowsOrder:
        - onboarding
        - login-with-validation
        - sign-up
        - sign-in
        - password-reset
        - revoke-session